#!/bin/bash

function createCentralBank() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/centralbank.coin.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/centralbank.coin.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-centralbank --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-centralbank.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-centralbank.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-centralbank.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-centralbank.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/centralbank.coin.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy centralbank's CA cert to centralbank's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/centralbank.coin.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/centralbank.coin.com/msp/tlscacerts/ca.crt"

  # Copy centralbank's CA cert to centralbank's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/centralbank.coin.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/centralbank.coin.com/tlsca/tlsca.centralbank.coin.com-cert.pem"

  # Copy centralbank's CA cert to centralbank's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/centralbank.coin.com/ca"
  cp "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/centralbank.coin.com/ca/ca.centralbank.coin.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-centralbank --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-centralbank --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-centralbank --id.name centralbankadmin --id.secret centralbankadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-centralbank -M "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/centralbank.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-centralbank -M "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls" --enrollment.profile tls --csr.hosts peer0.centralbank.coin.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/centralbank.coin.com/peers/peer0.centralbank.coin.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-centralbank -M "${PWD}/organizations/peerOrganizations/centralbank.coin.com/users/User1@centralbank.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/centralbank.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/centralbank.coin.com/users/User1@centralbank.coin.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://centralbankadmin:centralbankadminpw@localhost:7054 --caname ca-centralbank -M "${PWD}/organizations/peerOrganizations/centralbank.coin.com/users/Admin@centralbank.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/centralbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/centralbank.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/centralbank.coin.com/users/Admin@centralbank.coin.com/msp/config.yaml"
}

function createCommercialBank() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/commercialbank.coin.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/commercialbank.coin.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-commercialbank --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-commercialbank.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-commercialbank.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-commercialbank.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-commercialbank.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy commercialbank's CA cert to commercialbank's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/msp/tlscacerts/ca.crt"

  # Copy commercialbank's CA cert to commercialbank's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/tlsca/tlsca.commercialbank.coin.com-cert.pem"

  # Copy commercialbank's CA cert to commercialbank's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/ca"
  cp "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem" "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/ca/ca.commercialbank.coin.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-commercialbank --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-commercialbank --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-commercialbank --id.name commercialbankadmin --id.secret commercialbankadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-commercialbank -M "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-commercialbank -M "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls" --enrollment.profile tls --csr.hosts peer0.commercialbank.coin.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/peers/peer0.commercialbank.coin.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-commercialbank -M "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/users/User1@commercialbank.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/users/User1@commercialbank.coin.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://commercialbankadmin:commercialbankadminpw@localhost:8054 --caname ca-commercialbank -M "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/users/Admin@commercialbank.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/commercialbank/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/commercialbank.coin.com/users/Admin@commercialbank.coin.com/msp/config.yaml"
}

function createConsumer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/consumer.coin.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/consumer.coin.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-consumer --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-consumer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-consumer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-consumer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-consumer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/consumer.coin.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy consumer's CA cert to consumer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/consumer.coin.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.coin.com/msp/tlscacerts/ca.crt"

  # Copy consumer's CA cert to consumer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/consumer.coin.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.coin.com/tlsca/tlsca.consumer.coin.com-cert.pem"

  # Copy consumer's CA cert to consumer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/consumer.coin.com/ca"
  cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.coin.com/ca/ca.consumer.coin.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-consumer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-consumer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-consumer --id.name consumeradmin --id.secret consumeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/consumer.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls" --enrollment.profile tls --csr.hosts peer0.consumer.coin.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/consumer.coin.com/peers/peer0.consumer.coin.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.coin.com/users/User1@consumer.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/consumer.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.coin.com/users/User1@consumer.coin.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://consumeradmin:consumeradminpw@localhost:11054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.coin.com/users/Admin@consumer.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/consumer.coin.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.coin.com/users/Admin@consumer.coin.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/coin.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/coin.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/coin.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/coin.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/coin.com/msp/tlscacerts/tlsca.coin.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/coin.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/coin.com/tlsca/tlsca.coin.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/coin.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls" --enrollment.profile tls --csr.hosts orderer.coin.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/coin.com/orderers/orderer.coin.com/msp/tlscacerts/tlsca.coin.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/coin.com/users/Admin@coin.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/coin.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/coin.com/users/Admin@coin.com/msp/config.yaml"
}

createCentralBank
createCommercialBank
createConsumer
createOrderer
